[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_char = '⦙'
'''

# [[plugins]]
# repo = 'vim-airline/vim-airline'

# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'michaeljsmith/vim-indent-object'

# Color schemes
[[plugins]]
repo = 'wadackel/vim-dogrun'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set background=dark
  colorscheme iceberg
  let g:lightline = {
       \ 'colorscheme': 'iceberg',
       \ }
'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_sign_error = '✘'
  let g:ale_sign_warning = '⚠'
  let g:ale_lint_on_text_changed = 'never'
'''

